# Generated by Django 3.1.5 on 2021-01-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('card_number', models.IntegerField()),
                ('cvc', models.IntegerField()),
                ('expiration_date', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Card Data',
                'verbose_name_plural': 'Cards Data',
            },
        ),
    ]
