# Generated by Django 3.1.5 on 2021-01-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddata',
            old_name='cvc',
            new_name='card_cvc',
        ),
        migrations.RenameField(
            model_name='carddata',
            old_name='expiration_date',
            new_name='card_expirationDate',
        ),
        migrations.RenameField(
            model_name='carddata',
            old_name='name',
            new_name='card_name',
        ),
    ]
