# Generated by Django 3.1.5 on 2021-01-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210124_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='card_cvc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carddata',
            name='card_number',
            field=models.CharField(max_length=255),
        ),
    ]
